# Generated by Django 2.0.3 on 2024-04-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='WORKER',
        ),
        migrations.AddField(
            model_name='rating',
            name='BOOKINGS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Bookings'),
        ),
    ]
